const veggie = [
  {
    id: 1,
    name: "Tomato",
    price: "20",
    like: true,
    img: require("../assets/Tomato.jpg"),
    about: "This is a Hybrid Toamto ",
  },
  {
    id: 2,
    name: "Potato",
    price: "40",
    like: false,
    img: require("../assets/potato.jpg"),
    about: "This is a Country Potato ",
  },
  {
    id: 3,
    name: "Onion",
    price: "10",
    like: false,
    img: require("../assets/onion.jpg"),
    about: "This is a Hybrid Onion ",
  },
  {
    id: 4,
    name: "Country Onion",
    price: "30",
    like: true,
    img: require("../assets/countryOnion.jpg"),
    about: "This is a Hybrid CountryOnion",
  },
  {
    id: 5,
    name: "Garlic",
    price: "50",
    like: false,
    img: require("../assets/garlic.jpg"),
    about: "Fine Garlic From CountrySide ",
  },
  {
    id: 6,
    name: "Ginger",
    price: "60",
    like: false,
    img: require("../assets/garlic.jpg"),
    about: "Fine garlic for Better Health ",
  },
  {
    id: 7,
    name: "DrumStick",
    price: "30",
    like: false,
    img: require("../assets/drumStick.jpg"),
    about: "This is a Hybrid Deumstick",
  },
  {
    id: 8,
    name: "Carrot",
    price: "25",
    like: true,
    img: require("../assets/carrot.jpg"),
    about: "This is a Ooty Carrot ",
  },
  {
    id: 9,
    name: "BeetRoot",
    price: "50",
    like: true,
    img: require("../assets/Veg.jpg"),
    about: "BeetRoot ",
  },
];

export default veggie;
